# fly.toml app configuration file generated for goshort on 2025-07-05T23:01:09+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'goshort'
primary_region = 'cdg'

[build]
  [build.args]
    GO_VERSION = '1.24.4'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
